#line 2 "tableio.c"

#line 4 "tableio.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer table_yy_create_buffer
#define yy_delete_buffer table_yy_delete_buffer
#define yy_flex_debug table_yy_flex_debug
#define yy_init_buffer table_yy_init_buffer
#define yy_flush_buffer table_yy_flush_buffer
#define yy_load_buffer_state table_yy_load_buffer_state
#define yy_switch_to_buffer table_yy_switch_to_buffer
#define yyin table_yyin
#define yyleng table_yyleng
#define yylex table_yylex
#define yylineno table_yylineno
#define yyout table_yyout
#define yyrestart table_yyrestart
#define yytext table_yytext
#define yywrap table_yywrap
#define yyalloc table_yyalloc
#define yyrealloc table_yyrealloc
#define yyfree table_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE table_yyrestart(table_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int table_yyleng;

extern FILE *table_yyin, *table_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up table_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up table_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via table_yyrestart()), so that the user can continue scanning by
	 * just pointing table_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when table_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int table_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow table_yywrap()'s to do buffer switches
 * instead of setting up a fresh table_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void table_yyrestart (FILE *input_file  );
void table_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE table_yy_create_buffer (FILE *file,int size  );
void table_yy_delete_buffer (YY_BUFFER_STATE b  );
void table_yy_flush_buffer (YY_BUFFER_STATE b  );
void table_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void table_yypop_buffer_state (void );

static void table_yyensure_buffer_stack (void );
static void table_yy_load_buffer_state (void );
static void table_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER table_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE table_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE table_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE table_yy_scan_bytes (yyconst char *bytes,int len  );

void *table_yyalloc (yy_size_t  );
void *table_yyrealloc (void *,yy_size_t  );
void table_yyfree (void *  );

#define yy_new_buffer table_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        table_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            table_yy_create_buffer(table_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        table_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            table_yy_create_buffer(table_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define table_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *table_yyin = (FILE *) 0, *table_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int table_yylineno;

int table_yylineno = 1;

extern char *table_yytext;
#define yytext_ptr table_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up table_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	table_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 20
#define YY_END_OF_BUFFER 21
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[57] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   21,   20,
       18,   19,   12,   14,   20,   20,   13,   20,   16,   17,
       15,   10,   11,    9,   20,   20,    6,   20,    3,    5,
        4,    2,   18,   14,    0,    0,   13,   13,   13,   16,
       15,   10,    0,    0,    7,    6,    8,    3,    1,    0,
        0,    0,    0,   13,    7,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,    9,    9,    9,   10,   10,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        1,   11,    1,    1,   12,    1,    9,    9,    9,   10,

       10,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[13] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    4,    4,
        3,    4
    } ;

static yyconst flex_int16_t yy_base[63] =
    {   0,
        0,    0,   10,   13,   18,    0,   28,   37,   81,   82,
       78,   82,   82,   74,   42,   69,   68,    0,    0,   82,
       67,   59,   82,   82,   44,   51,   48,    0,    0,   82,
       82,   50,   45,   41,   37,    0,   47,    0,    0,    0,
       39,   41,   34,    0,   52,    0,    0,    0,   82,   28,
       29,   26,   27,   26,   25,   82,   62,   66,   13,   70,
       10,   74
    } ;

static yyconst flex_int16_t yy_def[63] =
    {   0,
       56,    1,   57,   57,   56,    5,   58,   58,   56,   56,
       56,   56,   56,   56,   56,   56,   15,   59,   60,   56,
       60,   56,   56,   56,   56,   56,   25,   61,   62,   56,
       56,   56,   56,   56,   56,   15,   56,   17,   59,   60,
       60,   56,   56,   25,   56,   27,   61,   62,   56,   56,
       56,   56,   56,   56,   56,    0,   56,   56,   56,   56,
       56,   56
    } ;

static yyconst flex_int16_t yy_nxt[95] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       10,   10,   20,   47,   21,   20,   39,   21,   10,   22,
       23,   24,   14,   25,   26,   27,   28,   28,   10,   10,
       30,   31,   55,   54,   55,   53,   54,   51,   32,   30,
       31,   45,   42,   41,   37,   34,   33,   32,   35,   36,
       43,   44,   50,   49,   37,   46,   51,   52,   45,   45,
       42,   53,   19,   19,   19,   19,   29,   29,   29,   29,
       40,   41,   40,   40,   48,   38,   37,   48,   34,   33,
       56,    9,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56

    } ;

static yyconst flex_int16_t yy_chk[95] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,   61,    3,    4,   59,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,   55,   54,   53,   52,   51,   50,    7,    8,
        8,   43,   42,   41,   35,   34,   33,    8,   15,   15,
       25,   25,   37,   32,   37,   27,   37,   45,   26,   45,
       22,   45,   57,   57,   57,   57,   58,   58,   58,   58,
       60,   21,   60,   60,   62,   17,   16,   62,   14,   11,
        9,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int table_yy_flex_debug;
int table_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *table_yytext;
#line 1 "tableio.lex"
#line 2 "tableio.lex"
/* -------------------------------------------------------------
   file: tableio.lex
   ------------------------------------------------------------- */
/* -------------------------------------------------------------
   Battelle Memorial Institute
   Pacific Northwest Laboratory
   ------------------------------------------------------------- */
/* -------------------------------------------------------------
   Created January 22, 1996 by William A. Perkins
   $Id: tableio.lex,v 1.4 2003/07/01 21:26:33 olivier Exp $
   ------------------------------------------------------------- */


const char* TABLE_LEX_ID = "$Id: tableio.lex,v 1.4 2003/07/01 21:26:33 olivier Exp $";

#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "tableio.h"
#include "errorhandler.h"
#include "settings.h"

static FILE *table_file = NULL;
static char *table_file_name = NULL;
static int table_lines = 1;
int table_errors = 0;
int table_warnings = 0;
static int table_field;
static int comment_caller, string_caller;

static char string_buffer[1024];

typedef enum {
  TABLE_END = -1,
  TABLE_RECORD = 0,
  TABLE_FIELD = 1
} TableStatus;

typedef struct {  
  int type;
  int integer;
  float real;
  char string[TABLE_MAX_FIELD_LEN];
} TableScanField;



/* -------------------------------------------------------------
   table_yy_lex 
   This is how the generated scanner is declared.  If an end of record
   is reached, zero is returned and field->type is set only if an
   unterminated string is found. At EOF, -1 is returned and
   field->type is set only for an unterminated string.  1 is returned,
   and field->type is set if a field is successfully read.
   ------------------------------------------------------------- */
#define YY_DECL static TableStatus table_yy_lex(TableScanField *field)


#line 569 "tableio.c"

#define INITIAL 0
#define comment_start 1
#define record_start 2
#define string_start 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int table_yylex_destroy (void );

int table_yyget_debug (void );

void table_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE table_yyget_extra (void );

void table_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *table_yyget_in (void );

void table_yyset_in  (FILE * in_str  );

FILE *table_yyget_out (void );

void table_yyset_out  (FILE * out_str  );

int table_yyget_leng (void );

char *table_yyget_text (void );

int table_yyget_lineno (void );

void table_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int table_yywrap (void );
#else
extern int table_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( table_yytext, table_yyleng, 1, table_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( table_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( table_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, table_yyin))==0 && ferror(table_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(table_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int table_yylex (void);

#define YY_DECL int table_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after table_yytext and table_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 71 "tableio.lex"



#line 758 "tableio.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! table_yyin )
			table_yyin = stdin;

		if ( ! table_yyout )
			table_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			table_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				table_yy_create_buffer(table_yyin,YY_BUF_SIZE );
		}

		table_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of table_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 57 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 82 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 74 "tableio.lex"
{ strncat(string_buffer, "\"", 1024); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "tableio.lex"
{ strncat(string_buffer, "\\", 1024); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "tableio.lex"
{ strncat(string_buffer, table_yytext, 1024); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "tableio.lex"
{ 
  field->type = TABLE_STRING;
  strncpy(field->string, string_buffer, TABLE_MAX_FIELD_LEN);
  BEGIN(string_caller);
  table_field++; 
  return(TABLE_FIELD);
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 85 "tableio.lex"
{ 
  field->type = TABLE_STRING;
  strncpy(field->string, string_buffer, TABLE_MAX_FIELD_LEN);
  BEGIN(string_caller);
  table_field++; 
  error_handler(ERRHDL_WARNING, 
                "%s: line %d, field %d: unterminated string field",
                table_file_name, table_lines, table_field);
  table_warnings++;
  yyless(0);
  return (TABLE_FIELD);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "tableio.lex"
{ 
  field->type = TABLE_INTEGER;
  field->integer = strtol(table_yytext, NULL, 10);
  ++table_field; 
  return (TABLE_FIELD);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "tableio.lex"
{ 
  field->type = TABLE_REAL;
  field->real = strtod(table_yytext, NULL);
  ++table_field;
  return (TABLE_FIELD);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "tableio.lex"
{ 
  field->type = TABLE_WORD;
  strncpy(field->string, table_yytext, TABLE_MAX_FIELD_LEN);
  ++table_field; 
  return (TABLE_FIELD);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 119 "tableio.lex"
{ string_caller = YY_START; BEGIN(string_start); 
                          string_buffer[0] = '\0'; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "tableio.lex"
{ /* eat it up */ }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 124 "tableio.lex"
{ 
  ++table_lines;
  BEGIN(INITIAL); 
  return (TABLE_RECORD);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "tableio.lex"
{ BEGIN(record_start); table_field = -1; yyless(0); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 132 "tableio.lex"
{ BEGIN(record_start); table_field = -1; yyless(0); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 134 "tableio.lex"
{ comment_caller = YY_START; BEGIN(comment_start); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 136 "tableio.lex"
{ /* eat up any of these within the comment */ }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 137 "tableio.lex"
{ /* eat up comments text */ }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 138 "tableio.lex"
{ BEGIN(comment_caller); yyless(0); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment_start):
case YY_STATE_EOF(record_start):
case YY_STATE_EOF(string_start):
#line 140 "tableio.lex"
{ 
  switch (YY_START) {
  case record_start:
  case comment_start:
    break;
  case string_start:
    field->type = TABLE_STRING;
    strncpy(field->string, string_buffer, TABLE_MAX_FIELD_LEN);
    table_warnings++;
    table_field++; 
    error_handler(ERRHDL_WARNING, 
                  "%s: line %d, field %d: unterminated string",
                  table_file_name, table_lines, table_field);
    break;
  default:
    table_field = -1;
    break;
  }
  BEGIN(INITIAL);
  return(TABLE_END);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "tableio.lex"
{ /* eat up extra white space */ }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 163 "tableio.lex"
{ table_lines++;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 165 "tableio.lex"
ECHO;
	YY_BREAK
#line 1009 "tableio.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed table_yyin at a new source and called
			 * table_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = table_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( table_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * table_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of table_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					table_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			table_yyrestart(table_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) table_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 57 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 57 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 56);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up table_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					table_yyrestart(table_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( table_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve table_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void table_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        table_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            table_yy_create_buffer(table_yyin,YY_BUF_SIZE );
	}

	table_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	table_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void table_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		table_yypop_buffer_state();
	 *		table_yypush_buffer_state(new_buffer);
     */
	table_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	table_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (table_yywrap()) processing, but the only time this flag
	 * is looked at is after table_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void table_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	table_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE table_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) table_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in table_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) table_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in table_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	table_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with table_yy_create_buffer()
 * 
 */
    void table_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		table_yyfree((void *) b->yy_ch_buf  );

	table_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a table_yyrestart() or at EOF.
 */
    static void table_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	table_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then table_yy_init_buffer was _probably_
     * called from table_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void table_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		table_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void table_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	table_yyensure_buffer_stack();

	/* This block is copied from table_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from table_yy_switch_to_buffer. */
	table_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void table_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	table_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		table_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void table_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)table_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in table_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)table_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in table_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE table_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) table_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in table_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	table_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to table_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       table_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE table_yy_scan_string (yyconst char * yystr )
{
    
	return table_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to table_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE table_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) table_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in table_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = table_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in table_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up table_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		table_yytext[table_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = table_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		table_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int table_yyget_lineno  (void)
{
        
    return table_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *table_yyget_in  (void)
{
        return table_yyin;
}

/** Get the output stream.
 * 
 */
FILE *table_yyget_out  (void)
{
        return table_yyout;
}

/** Get the length of the current token.
 * 
 */
int table_yyget_leng  (void)
{
        return table_yyleng;
}

/** Get the current token.
 * 
 */

char *table_yyget_text  (void)
{
        return table_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void table_yyset_lineno (int  line_number )
{
    
    table_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see table_yy_switch_to_buffer
 */
void table_yyset_in (FILE *  in_str )
{
        table_yyin = in_str ;
}

void table_yyset_out (FILE *  out_str )
{
        table_yyout = out_str ;
}

int table_yyget_debug  (void)
{
        return table_yy_flex_debug;
}

void table_yyset_debug (int  bdebug )
{
        table_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from table_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    table_yyin = stdin;
    table_yyout = stdout;
#else
    table_yyin = (FILE *) 0;
    table_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * table_yylex_init()
     */
    return 0;
}

/* table_yylex_destroy is for both reentrant and non-reentrant scanners. */
int table_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		table_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		table_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	table_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * table_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *table_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *table_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void table_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see table_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 165 "tableio.lex"



/* -------------------------------------------------------------
   table_open

   opens the specified file and sets up the scanner.  Zero is returned
   if all goes well
   ------------------------------------------------------------- */
int
table_open(const char *filename) 
{
  if (table_file != NULL) {
    error_handler(ERRHDL_ERROR,
                 "table_open: already reading another table: %s",
                 table_file_name);
    return (-1);
  } 
  if ((table_file = fopen(filename, "r")) == NULL) {
    error_handler(ERRHDL_ERROR,
                 "table_open: can not open file \"%s\": %s",
                 filename, strerror(errno));
    table_file = NULL;
    return (-1);
  }
  table_file_name = (char *)strdup(filename);
  table_lines = 1;
  table_errors = 0;  
  table_warnings = 0;
  table_yyrestart(table_file);
  return (0);
}
  

/* -------------------------------------------------------------
   handle_field
   ------------------------------------------------------------- */
static int
handle_field(TableScanField *field, int nfields, TableField *fld_defn) 
{
  int i;
  int err = 0;
  
  if (field->type == fld_defn[0].type) {
    switch (field->type) {

    case TABLE_INTEGER:

      fld_defn[0].value.integer = field->integer;
      fld_defn[0].read = TRUE;
      break;

    case TABLE_REAL:

      fld_defn[0].value.real = field->real;
      fld_defn[0].read = TRUE;
      break;

    case TABLE_STRING:

      strncpy(fld_defn[0].field, field->string, TABLE_MAX_FIELD_LEN);
      fld_defn[0].read = TRUE;
      break;

    case TABLE_WORD:

      for (i = 0; fld_defn[0].words[i] != NULL; i++) {
        if (!strncmp(fld_defn[0].words[i], 
                     field->string, TABLE_MAX_FIELD_LEN)) {
          fld_defn[0].value.integer = i;
          fld_defn[0].read = TRUE;
          break;
        }
      }
      if (!fld_defn[0].read) {
        err++;
        error_handler(ERRHDL_ERROR, 
                      "%s: line %d, field %d: unknown keyword \"%s\"",
                      (const char *)table_file_name, 
                      (int)table_lines, (int)table_field, 
                      (const char *)field->string);
      }
      break;

    default:

      error_handler(ERRHDL_FATAL, 
                    "handle_field: what is this status: %d?", 
                    field->type);
      break;
          
    }
      
  } else if (field->type == TABLE_INTEGER && 
             fld_defn[0].type == TABLE_REAL) {

    fld_defn[0].value.real = field->integer;
    fld_defn[0].read = TRUE;

  } else if (fld_defn[0].required) {

    err++;
    error_handler(ERRHDL_ERROR, 
                  "%s: line %d, field %d: type mismatch",
                  table_file_name, table_lines, table_field);

  } else {

    error_handler(ERRHDL_STATUS,
                  "%s: line %d, field %d: type mismatch for optional \"%s\"",
                  table_file_name, table_lines, table_field,
                  fld_defn[0].name);
    if (--nfields > 0) {
      err += handle_field(field, nfields, &fld_defn[1]);
    } else {
      error_handler(ERRHDL_ERROR, 
                    "%s: line %d, field %d: unable to match field",
                    table_file_name, table_lines, table_field);
    }

  }
  return (err);
}
  

/* -------------------------------------------------------------
   table_get_fields

   This is used to read a record from the file and decide if errors
   have occurred. Zero is returned if a record is read OK, -1 if the
   end of file was reached, a positive integer if errors occured.
   This assumes table_open has been called.
   ------------------------------------------------------------- */
int
table_get_fields(int nfields, TableField *fld_defn) 
{
  int i, required;
  int err = 0;
  char done = FALSE;
  TableStatus status = TABLE_END;
  TableScanField field;

  error_handler(ERRHDL_DEBUG, 
                "%s: line %d: table_scan_record: looking for %d fields",
                table_file_name, table_lines, nfields);

  for (i = 0, required = 0; i < nfields; i++) {
    if (fld_defn[i].required) required++;
    fld_defn[i].read = FALSE;
    fld_defn[i].value.real = 0.0;
    strcpy(fld_defn[i].field, "\0");
  }
  
  while (!done) { 
    switch (status = table_yy_lex(&field)) {

    case TABLE_END:
    case TABLE_RECORD:
      if (table_field >= 0) {
        for (i = 0; i < nfields; i++) {
          if (fld_defn[i].required && !fld_defn[i].read) {
            err++;
            error_handler(ERRHDL_ERROR,
                          "%s: line %d: \"%s\" (field %d) required but not read",
                          table_file_name, table_lines,
                          fld_defn[i].name, i + 1);
          }
        }
      }
      done = TRUE;
      break;

    case TABLE_FIELD:

      if (table_field >= nfields) {
        err++;
        error_handler(ERRHDL_ERROR,
                      "%s: line %d, field %d: too many fields, expected %d",
                      table_file_name, table_lines, table_field, nfields);
        continue;
      }

      err += handle_field(&field, nfields - table_field, &fld_defn[table_field]);
      break;

    default:

      error_handler(ERRHDL_FATAL, 
                    "table_get_fields: what is this status: %d?", 
                    status);
      break;
          
    }
  }
  
  table_errors += err;

  if (status == TABLE_END)
    return (-1);

  return (err);
}

/* -------------------------------------------------------------
   table_lineno
   ------------------------------------------------------------- */
int
table_lineno(void)
{
  return table_lines;
}



/* -------------------------------------------------------------
   table_close
   ------------------------------------------------------------- */
void
table_close(void) 
{
  if (fclose(table_file) != 0) {
    error_handler(ERRHDL_WARNING,
                  "table_close: %s: error closing",
                  table_file_name, strerror(errno));
  }
  table_file = NULL;
  if (table_file_name != NULL) {
    free(table_file_name);
    table_file_name = NULL;
  }
  
}


#ifdef TEST_MAIN

typedef enum { ONE, TWO, THREE } RecordWord;
typedef struct _record_ {
  int ID;
  float value;
  RecordWord item;
  char *comment;
  struct _record_ *next;
} Record;

/* -------------------------------------------------------------
   Main Program
   ------------------------------------------------------------- */
int
main(int argc, char **argv)
{
  int status, i, rec, done;
  static char *crown_words[4] = { 
    "ONE", "TWO", "THREE", NULL 
  };
  static const int nfields = 4;
  static TableField fldesc[4] = {
    {
      "ID",
      TABLE_INTEGER,
      TRUE, FALSE,
      0.0, "", NULL
    },
    {
      "Channel Width",
      TABLE_REAL,
      TRUE, FALSE,
      0.0, "", NULL
    },
    {
      "Road Crown Type",
      TABLE_WORD,
      FALSE, FALSE,
      0.0, "", crown_words
    },
    {
      "Comment",
      TABLE_STRING,
      FALSE, FALSE,
      0.0, "", NULL
    }
  };
  static const char *file = "table_test.dat";

  error_handler_init(argv[0], NULL, ERRHDL_DEBUG);
  
  if (table_open(file) != 0) {
    error_handler(ERRHDL_ERROR, 
                  "channel_read_classes: unable to open file \"%s\": %s",
                  file, strerror(errno));
    exit(1);
  }

  printf("Successfully read stuff:\n\n");
    
  rec = 0;
  done = FALSE;
  while (!done) {
    done = ((status = table_get_fields(nfields, fldesc)) < 0);
    printf("Record %d:\n", ++rec);
    for (i = 0; i < nfields; i++) {
      printf("\t%20s:\t", fldesc[i].name);
      if (fldesc[i].read) {
        switch (fldesc[i].type) {
        case TABLE_INTEGER:
          printf("%d (INTEGER)\n", fldesc[i].value.integer);
          break;
        case TABLE_REAL:
          printf("%g (REAL)\n", (double)fldesc[i].value.real);
          break;
        case TABLE_WORD:
          printf("%s (WORD, index = %d)\n", 
                 fldesc[i].words[fldesc[i].value.integer],
                 fldesc[i].value.integer);
          break;
        case TABLE_STRING:
          printf("%s (STRING)\n", fldesc[i].field);
          break;
        default:
          error_handler(ERRHDL_ERROR,
                        "main: what is this type: %d?",
                        fldesc[i].type);
          break;
        }
      } else {
        printf("not read\n");
      }
    }
  }
  
  error_handler(ERRHDL_MESSAGE,
                "%s: %d errors, %d warnings",
                file, table_errors, table_warnings);
  error_handler_done();
  exit(0);
}



#endif

